SELECT R.Name, A.Name, COUNT(StreamDate) AS N 
FROM ACTOR A 
JOIN MOVIE_ACTOR USING (ActorId)
JOIN MOVIE M USING (MovieId) 
JOIN CUSTOMER C USING (CustomerId)
JOIN COUNTRY CO ON (C.Country = CO.Name)
JOIN REGION R USING(RegionId)
FULL OUTER JOIN STREAM USING (MovieId)
WHERE A.Name LIKE 'Tom%' AND R.Name IS NOT NULL
GROUP BY R.Name, A.Name 
ORDER BY R.Name, A.Name DESC;