SELECT
A1.Name, A2.Name, COUNT(MovieId) AS N FROM
(MOVIE_ACTOR MA1 NATURAL JOIN ACTOR A1)
JOIN (MOVIE_ACTOR MA2 NATURAL JOIN ACTOR A2) USING (MovieId)
NATURAL JOIN MOVIE
WHERE A1.Name < A2.Name
GROUP BY A1.Name, A2.Name DESC
HAVING N >= 4
ORDER BY N DESC, A1.Name, A2.Name;